name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm intsall
        run: npm i

      - name: Deploy
        if: contains(env.GITHUB_COMMIT_MESSAGE, 'Deploy version') == false
        run: npm run deploy
