name: Linter

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm intsall
        uses: npm i

      - name: lint
        uses: npm run lint
